spring:
  application:
    name: spring-jpa
  datasource:    url: jdbc:mysql://localhost:3306/db
    username: root
    password: welcome
  jpa:    hibernate:      ddl-auto: create
    show-sql: true  