server:
  port: 8070
eureka:  client:    service-url:      defaultzone: http://localhost:8761/eureka/
spring:  boot:    admin:      client:        url: http://localhost:7000  application:    name: product-service
management:  endpoints:    web:      exposure:        include: '*'               